/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package usage;

import TableModels.ProdutosModelsToUsage;
import br.com.tanamao.dal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author hugog
 */
public class panel4 extends javax.swing.JPanel {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ProdutosModelsToUsage modelo;

    public panel4(int step) {
        initComponents();
        conexao = ModuloConexao.conector();
        modelo = new ProdutosModelsToUsage();
        reviewItens.setModel(modelo);
        reviewItens.getTableHeader().setResizingAllowed(false);
        reviewItens.getTableHeader().setReorderingAllowed(false);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollButton1 = new ArchiveTablesVendas.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reviewItens = new javax.swing.JTable();
        btRemoveProduto = new javax.swing.JButton();
        btLimparCaixa = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        reviewItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(reviewItens);

        tableScrollButton1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btRemoveProduto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btRemoveProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/caixa-aberta (1).png"))); // NOI18N
        btRemoveProduto.setText("Remover item");
        btRemoveProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveProdutoActionPerformed(evt);
            }
        });

        btLimparCaixa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btLimparCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/cancelar_1.png"))); // NOI18N
        btLimparCaixa.setText("Limpar caixa");
        btLimparCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimparCaixa)
                        .addGap(18, 18, 18)
                        .addComponent(btRemoveProduto)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemoveProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoveProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveProdutoActionPerformed
        // TODO add your handling code here:
//        int setarNote = tableItensBox.getSelectedRow();
//        if (setarNote >= 0) {
//            int getrow = tableItensBox.getSelectedRow();
//            String getid = (tableItensBox.getModel().getValueAt(getrow, 0).toString());
//            removeforCaixa(getid, "");
//        } else {
//            Notification noti = new Notification(this, Notification.Type.INFO, Notification.Location.TOP_CENTER, "Selecione um item para poder retirar da caixa!");
//            noti.showNotification();
//        }
    }//GEN-LAST:event_btRemoveProdutoActionPerformed

    private void btLimparCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCaixaActionPerformed
//        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja limpar a caixa?", "Atenção", JOptionPane.YES_NO_OPTION);
//        if (confirma == JOptionPane.YES_OPTION) {
//            int rowcount = tableItensBox.getRowCount();
//            for (int i = 0; i < rowcount; i++) {
//                String id = (tableItensBox.getModel().getValueAt(i, 0).toString());
//                removeforCaixa(id, "");
//            }
//            Notification noti = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_CENTER, "Caixa limpa com sucesso!");
//            noti.showNotification();
//        }
    }//GEN-LAST:event_btLimparCaixaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimparCaixa;
    private javax.swing.JButton btRemoveProduto;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable reviewItens;
    private ArchiveTablesVendas.TableScrollButton tableScrollButton1;
    // End of variables declaration//GEN-END:variables
}
