/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pagesSearchs;

import pagesCadastro.TelaCadUser;
import br.com.tanamao.dal.ModuloConexao;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import static pages.TelaPrincipal.empresa;
import static pagesCadastro.TelaCadUser.avatar1;
import static pagesCadastro.TelaCadUser.avatar2;
import static pagesCadastro.TelaCadUser.avatar3;
import static pagesCadastro.TelaCadUser.avatar4;
import static pagesCadastro.TelaCadUser.avatar5;
import static pagesCadastro.TelaCadUser.avatar6;
import static pagesCadastro.TelaCadUser.avatar7;
import textFieldSearch.SearchOptinEvent;
import textFieldSearch.SearchOption;

/**
 *
 * @author hugogabriel
 */
public class SearchUsuario extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form SearchUsuario
     */
    public SearchUsuario() {
        initComponents();
        setIcon();
        conexao = ModuloConexao.conector();
        colocarDados();
        setColorFromEmpresa();

        txProcurar.addEventOptionSelected(new SearchOptinEvent() {
            @Override
            public void optionSelected(SearchOption option, int index) {
                txProcurar.setHint("Procurar por " + option.getName() + "....");
                txProcurar.setText(null);
            }
        });

        txProcurar.addOption(new SearchOption("Nome, login", new ImageIcon(getClass().getResource("/src/user.png"))));
        txProcurar.addOption(new SearchOption("Empresa", new ImageIcon(getClass().getResource("/src/tel.png"))));
        txProcurar.addOption(new SearchOption("E-mail", new ImageIcon(getClass().getResource("/src/email.png"))));
        txProcurar.setSelectedIndex(0);
        pesquisar_user("");

    }

    public void setColorFromEmpresa() {
        String empresaSelected = empresa.getText();
        if (empresaSelected.equals("docatec")) {
            jPanel2.setBackground(new Color(15, 102, 122));
        } else {
            jPanel2.setBackground(new Color(147, 167, 39));
        }
    }

    private void pesquisar_user(String where, Object... search) {

        String sql = "select nome as Nome,login as Login,perfil as Perfil, empresa as Empresa from usuarios " + where + "";
        try {

            pst = conexao.prepareStatement(sql);

            for (int i = 0; i < search.length; i++) {
                pst.setObject(i + 1, search[i]);
            }
            rs = pst.executeQuery();
            tbUsers.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/src/mark 2.7.png")));
    }

    public void colocarDados() {
        String sql = "select nome as Nome,login as Login,perfil as Perfil,empresa as Empresa from usuarios order by nome";
        try {
            pst = conexao.prepareStatement(sql);

            rs = pst.executeQuery();
            tbUsers.setModel(DbUtils.resultSetToTableModel(rs));


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txProcurar = new textFieldSearch.TextFieldSearchOption();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de usuários");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(147, 167, 39));

        txProcurar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txProcurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txProcurarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbUsers.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Fone", "Login", "Título 4"
            }
        ));
        tbUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsers);

        btCancel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/excluirUser.png"))); // NOI18N
        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:     
        this.dispose();
        TelaCadUser.btSearch2.setEnabled(true);
    }//GEN-LAST:event_btCancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        TelaCadUser.btSearch2.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void tbUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsersMouseClicked
        // TODO add your handling code here:
        String getLogin = tbUsers.getValueAt(tbUsers.getSelectedRow(), 1).toString();
        String sql = "select idusuarios,nome,email,login,senha,perfil,avatar,empresa from usuarios where login = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, getLogin);
            rs = pst.executeQuery();

            while (rs.next()) {
                String id = rs.getString(1);
                String Nome = rs.getString(2);
                String Email = rs.getString(3);
                String Login = rs.getString(4);
                String Senha = rs.getString(5);
                String Perfil = rs.getString(6);
                String Avatar = rs.getString(7);
                String empresa = rs.getString(8);

                if (Avatar.equals("avatar1")) {
                    TelaCadUser.iduserx.setText(id);
                    TelaCadUser.txNome.setText(Nome);
                    TelaCadUser.txMail.setText(Email);
                    TelaCadUser.txLogin.setText(Login);
                    TelaCadUser.txPass.setText(Senha);
                    TelaCadUser.cbPerfil.setSelectedItem(Perfil);
                    TelaCadUser.avatar1.setSelected(true);
                    avatar1.setSelected(true);
                    TelaCadUser.btCad1.setEnabled(false);
                    TelaCadUser.btEdit1.setEnabled(true);
                    TelaCadUser.btExcluir1.setEnabled(true);
                    if (empresa.equals("tanamao")) {
                        TelaCadUser.cbEmpresa.setSelectedItem("tanamao");
                    } else {
                        TelaCadUser.cbEmpresa.setSelectedItem("docatec");
                    }
                    this.dispose();

                }
                if (Avatar.equals("avatar2")) {
                    TelaCadUser.iduserx.setText(id);
                    TelaCadUser.txNome.setText(Nome);
                    TelaCadUser.txMail.setText(Email);
                    TelaCadUser.txLogin.setText(Login);
                    TelaCadUser.txPass.setText(Senha);
                    TelaCadUser.cbPerfil.setSelectedItem(Perfil);

                    avatar2.setSelected(true);

                    TelaCadUser.btCad1.setEnabled(false);
                    TelaCadUser.btEdit1.setEnabled(true);
                    TelaCadUser.btExcluir1.setEnabled(true);
                    if (empresa.equals("tanamao")) {
                        TelaCadUser.cbEmpresa.setSelectedItem("tanamao");
                    } else {
                        TelaCadUser.cbEmpresa.setSelectedItem("docatec");
                    }
                    this.dispose();
                }
                if (Avatar.equals("avatar3")) {
                    TelaCadUser.iduserx.setText(id);
                    TelaCadUser.txNome.setText(Nome);
                    TelaCadUser.txMail.setText(Email);
                    TelaCadUser.txLogin.setText(Login);
                    TelaCadUser.txPass.setText(Senha);
                    TelaCadUser.cbPerfil.setSelectedItem(Perfil);

                    avatar3.setSelected(true);

                    TelaCadUser.btCad1.setEnabled(false);
                    TelaCadUser.btEdit1.setEnabled(true);
                    TelaCadUser.btExcluir1.setEnabled(true);
                    if (empresa.equals("tanamao")) {
                        TelaCadUser.cbEmpresa.setSelectedItem("tanamao");
                    } else {
                        TelaCadUser.cbEmpresa.setSelectedItem("docatec");
                    }
                    this.dispose();
                }
                if (Avatar.equals("avatar4")) {
                    TelaCadUser.iduserx.setText(id);
                    TelaCadUser.txNome.setText(Nome);
                    TelaCadUser.txMail.setText(Email);
                    TelaCadUser.txLogin.setText(Login);
                    TelaCadUser.txPass.setText(Senha);
                    TelaCadUser.cbPerfil.setSelectedItem(Perfil);

                    avatar4.setSelected(true);

                    TelaCadUser.btCad1.setEnabled(false);
                    TelaCadUser.btEdit1.setEnabled(true);
                    TelaCadUser.btExcluir1.setEnabled(true);
                    if (empresa.equals("tanamao")) {
                        TelaCadUser.cbEmpresa.setSelectedItem("tanamao");
                    } else {
                        TelaCadUser.cbEmpresa.setSelectedItem("docatec");
                    }
                    this.dispose();
                }
                if (Avatar.equals("avatar5")) {
                    TelaCadUser.iduserx.setText(id);
                    TelaCadUser.txNome.setText(Nome);
                    TelaCadUser.txMail.setText(Email);
                    TelaCadUser.txLogin.setText(Login);
                    TelaCadUser.txPass.setText(Senha);
                    TelaCadUser.cbPerfil.setSelectedItem(Perfil);

                    avatar5.setSelected(true);

                    TelaCadUser.btCad1.setEnabled(false);
                    TelaCadUser.btEdit1.setEnabled(true);
                    TelaCadUser.btExcluir1.setEnabled(true);
                    if (empresa.equals("tanamao")) {
                        TelaCadUser.cbEmpresa.setSelectedItem("tanamao");
                    } else {
                        TelaCadUser.cbEmpresa.setSelectedItem("docatec");
                    }
                    this.dispose();
                }
                if (Avatar.equals("avatar6")) {
                    TelaCadUser.iduserx.setText(id);
                    TelaCadUser.txNome.setText(Nome);
                    TelaCadUser.txMail.setText(Email);
                    TelaCadUser.txLogin.setText(Login);
                    TelaCadUser.txPass.setText(Senha);
                    TelaCadUser.cbPerfil.setSelectedItem(Perfil);

                    avatar6.setSelected(true);

                    TelaCadUser.btCad1.setEnabled(false);
                    TelaCadUser.btEdit1.setEnabled(true);
                    TelaCadUser.btExcluir1.setEnabled(true);
                    if (empresa.equals("tanamao")) {
                        TelaCadUser.cbEmpresa.setSelectedItem("tanamao");
                    } else {
                        TelaCadUser.cbEmpresa.setSelectedItem("docatec");
                    }
                    this.dispose();
                }
                if (Avatar.equals("avatar7")) {
                    TelaCadUser.iduserx.setText(id);
                    TelaCadUser.txNome.setText(Nome);
                    TelaCadUser.txMail.setText(Email);
                    TelaCadUser.txLogin.setText(Login);
                    TelaCadUser.txPass.setText(Senha);
                    TelaCadUser.cbPerfil.setSelectedItem(Perfil);

                    avatar7.setSelected(true);

                    TelaCadUser.btCad1.setEnabled(false);
                    TelaCadUser.btEdit1.setEnabled(true);
                    TelaCadUser.btExcluir1.setEnabled(true);
                    if (empresa.equals("tanamao")) {
                        TelaCadUser.cbEmpresa.setSelectedItem("tanamao");
                    } else {
                        TelaCadUser.cbEmpresa.setSelectedItem("docatec");
                    }
                    this.dispose();
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbUsersMouseClicked

    private void txProcurarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txProcurarKeyReleased
        // TODO add your handling code here:
        if (txProcurar.isSelected()) {
            int option = txProcurar.getSelectedIndex();
            String text = "%" + txProcurar.getText() + "%";
            if (option == 0) {
                pesquisar_user("where nome like ? or login like ?", text, text);
            } else if (option == 1) {
                pesquisar_user("where empresa like ?", text);
            } else if (option == 2) {
                pesquisar_user("where email like ?", text);
            }
        }
    }//GEN-LAST:event_txProcurarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUsers;
    private textFieldSearch.TextFieldSearchOption txProcurar;
    // End of variables declaration//GEN-END:variables

}
