/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages;

import javax.swing.ImageIcon;

/**
 *
 * @author Hugo Gabriel
 */
public class PageEtiquetaNotebook extends javax.swing.JFrame {

    /**
     * Creates new form PageEtiquetaNotebook
     */
    public PageEtiquetaNotebook() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        EtiquetaNotebook = new javax.swing.JComboBox<>();
        btViewEtiquetaNotebook = new javax.swing.JButton();
        ImprimirCarregador = new javax.swing.JButton();
        EtiquetaCarregador = new javax.swing.JComboBox<>();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        ImprimirCaixa = new javax.swing.JButton();
        EtiquetaCaixa = new javax.swing.JComboBox<>();
        jCheckBox5 = new javax.swing.JCheckBox();
        btViewEtiquetaNotebook1 = new javax.swing.JButton();
        ImprimirCarregador1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox1.setText("Etiqueta para o notebook");

        EtiquetaNotebook.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        EtiquetaNotebook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etiqueta Simples", "Etiqueta Detalhada", "Etiqueta Code" }));

        btViewEtiquetaNotebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/visao.png"))); // NOI18N

        ImprimirCarregador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/impressora.png"))); // NOI18N

        EtiquetaCarregador.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        EtiquetaCarregador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox4.setText("Etiqueta para o carregador");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/visao.png"))); // NOI18N

        ImprimirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/impressora.png"))); // NOI18N

        EtiquetaCaixa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        EtiquetaCaixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox5.setText("Etiqueta para caixa");

        btViewEtiquetaNotebook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/visao.png"))); // NOI18N

        ImprimirCarregador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/impressora.png"))); // NOI18N
        ImprimirCarregador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirCarregador1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtiquetaNotebook, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EtiquetaCarregador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EtiquetaCaixa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5))
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btViewEtiquetaNotebook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ImprimirCarregador))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ImprimirCaixa))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btViewEtiquetaNotebook1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ImprimirCarregador1)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaNotebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImprimirCarregador1)
                    .addComponent(btViewEtiquetaNotebook1))
                .addGap(12, 12, 12)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaCarregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImprimirCarregador)
                    .addComponent(btViewEtiquetaNotebook))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImprimirCaixa)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/excluirUser.png"))); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        ImageIcon icon = new ImageIcon(getClass().getResource("/src/digitalizacao.gif"));
//        icon.setImage(icon.getImage().getScaledInstance(btViewEtiquetaNotebook.getWidth(), btViewEtiquetaNotebook.getHeight(), 1));
//        btViewEtiquetaNotebook.setIcon(icon);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ImprimirCarregador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirCarregador1ActionPerformed
        // TODO add your handling code here:
        //        int setarNotes = tableNotebooks.getSelectedRow();
//        int confirma = JOptionPane.showConfirmDialog(null, "Confirmar a impressão deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
//        if (confirma == JOptionPane.YES_OPTION) {
//            try {
//                String sql;
//                sql = "select * from notebooks where idnotebooks =?";
//                pst = conexao.prepareStatement(sql);
//                pst.setString(1, tableNotebooks.getModel().getValueAt(setarNotes, 0).toString());
//                rs = pst.executeQuery();
//                InputStream report = getClass().getResourceAsStream("/JSP/EtiquetaNotebook.jasper");
//
//                String os = System.getProperty("os.name");
//                if (os.startsWith("Windows")) {
//
//                    JRResultSetDataSource relatResul = new JRResultSetDataSource(rs);
//                    JasperPrint jasperPrint = JasperFillManager.fillReport(report, new HashMap(), relatResul);
//                    JasperExportManager.exportReportToPdfFile(jasperPrint, "C://convtech/EtiquetaNotebook.pdf");
//                    File file = new File("C://convtech/EtiquetaNotebook.pdf");
//
//                    try {
//                        Desktop.getDesktop().open(file);
//                    } catch (Exception e) {
//                        JOptionPane.showMessageDialog(null, e);
//                    }
//                }
//
//                if (os.startsWith("Mac")) {
//
//                    JRResultSetDataSource relatResul = new JRResultSetDataSource(rs);
//                    JasperPrint jasperPrint = JasperFillManager.fillReport(report, new HashMap(), relatResul);
//                    JasperExportManager.exportReportToPdfFile(jasperPrint, "/Users/hugogabriel/Desktop/Tanamao/EtiquetaNotebook.pdf");
//                    File file = new File("/Users/hugogabriel/Desktop/Tanamao/EtiquetaNotebook.pdf");
//
//                    try {
//                        Desktop.getDesktop().open(file);
//                    } catch (Exception e) {
//                        JOptionPane.showMessageDialog(null, e);
//                    }
//
//                }
//
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, e);
//            }
//
//        }
    }//GEN-LAST:event_ImprimirCarregador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageEtiquetaNotebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageEtiquetaNotebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageEtiquetaNotebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageEtiquetaNotebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageEtiquetaNotebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EtiquetaCaixa;
    private javax.swing.JComboBox<String> EtiquetaCarregador;
    private javax.swing.JComboBox<String> EtiquetaNotebook;
    private javax.swing.JButton ImprimirCaixa;
    private javax.swing.JButton ImprimirCarregador;
    private javax.swing.JButton ImprimirCarregador1;
    private javax.swing.JButton btViewEtiquetaNotebook;
    private javax.swing.JButton btViewEtiquetaNotebook1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
