/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package compras;

/**
 *
 * @author hugog
 */
public class RevisarProdutos extends javax.swing.JPanel {

    /**
     * Creates new form RevisarProdutos
     */
    public RevisarProdutos(int step) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLimparCaixa = new javax.swing.JButton();
        btRemoveProduto = new javax.swing.JButton();
        tableScrollButton1 = new ArchiveTablesVendas.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reviewItens = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        btLimparCaixa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btLimparCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/cancelar_1.png"))); // NOI18N
        btLimparCaixa.setText("Limpar lista");
        btLimparCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCaixaActionPerformed(evt);
            }
        });

        btRemoveProduto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btRemoveProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/caixa-aberta (1).png"))); // NOI18N
        btRemoveProduto.setText("Remover produto");
        btRemoveProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveProdutoActionPerformed(evt);
            }
        });

        reviewItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(reviewItens);

        tableScrollButton1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimparCaixa)
                        .addGap(18, 18, 18)
                        .addComponent(btRemoveProduto)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemoveProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCaixaActionPerformed
        //        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja limpar a caixa?", "Atenção", JOptionPane.YES_NO_OPTION);
        //        if (confirma == JOptionPane.YES_OPTION) {
            //            int rowcount = tableItensBox.getRowCount();
            //            for (int i = 0; i < rowcount; i++) {
                //                String id = (tableItensBox.getModel().getValueAt(i, 0).toString());
                //                removeforCaixa(id, "");
                //            }
            //            Notification noti = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_CENTER, "Caixa limpa com sucesso!");
            //            noti.showNotification();
            //        }
    }//GEN-LAST:event_btLimparCaixaActionPerformed

    private void btRemoveProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveProdutoActionPerformed
        // TODO add your handling code here:
        //        int setarNote = tableItensBox.getSelectedRow();
        //        if (setarNote >= 0) {
            //            int getrow = tableItensBox.getSelectedRow();
            //            String getid = (tableItensBox.getModel().getValueAt(getrow, 0).toString());
            //            removeforCaixa(getid, "");
            //        } else {
            //            Notification noti = new Notification(this, Notification.Type.INFO, Notification.Location.TOP_CENTER, "Selecione um item para poder retirar da caixa!");
            //            noti.showNotification();
            //        }
    }//GEN-LAST:event_btRemoveProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimparCaixa;
    private javax.swing.JButton btRemoveProduto;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable reviewItens;
    private ArchiveTablesVendas.TableScrollButton tableScrollButton1;
    // End of variables declaration//GEN-END:variables
}
