/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DetailParteEPecas;

import br.com.tanamao.dal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static pagesDetails.PPDetails.idPP0001;

/**
 *
 * @author Hugo G
 */
public class PainelPP11 extends javax.swing.JPanel {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public PainelPP11() {
        initComponents();
        conexao = ModuloConexao.conector();
        getDadosGerais();
    }

        public void getDadosGerais() {

        String getID = idPP0001.getText();

        try {
            String sql = "select * from partepecas where idpartepecas like ?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, getID);

            rs = pst.executeQuery();

            while (rs.next()) {
//                descricao1.setText(rs.getString(3));
//                codebar1.setText(rs.getString(2));
//                ref1.setText(rs.getString(4));
//                grupo1.setText(rs.getString(5));
//                subgrupo1.setText(rs.getString(6));
//                marca1.setText(rs.getString(7));
//                modelo1.setText(rs.getString(8));
//                serial1.setText(rs.getString(9));
//                forne1.setText(rs.getString(10));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        codebarREFS = new javax.swing.JTextField();
        serialREFS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        skuforneREFS = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        PartNumberREFS = new javax.swing.JTextField();
        RefsFromREFS = new javax.swing.JTextField();
        UniqREFS = new javax.swing.JTextField();
        ClassREFS = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Código de barras");

        codebarREFS.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N

        serialREFS.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Serial Number");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("SKU Fornecedor");

        skuforneREFS.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N

        jLabel53.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel53.setText("P/N");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("REF. GERAL");

        jLabel51.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel51.setText("REF. CLASSIFICATIVA");

        jLabel52.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel52.setText("REF. ÚNICA");

        PartNumberREFS.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N

        RefsFromREFS.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N

        UniqREFS.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N

        ClassREFS.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(serialREFS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PartNumberREFS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RefsFromREFS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UniqREFS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClassREFS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skuforneREFS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 357, Short.MAX_VALUE))
                            .addComponent(codebarREFS, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(232, 232, 232))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codebarREFS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(serialREFS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skuforneREFS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PartNumberREFS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RefsFromREFS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel51)
                .addGap(16, 16, 16)
                .addComponent(ClassREFS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel52)
                .addGap(18, 18, 18)
                .addComponent(UniqREFS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modelo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelo4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField ClassREFS;
    public static javax.swing.JTextField PartNumberREFS;
    public static javax.swing.JTextField RefsFromREFS;
    public static javax.swing.JTextField UniqREFS;
    public static javax.swing.JTextField codebarREFS;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JTextField serialREFS;
    public static javax.swing.JTextField skuforneREFS;
    // End of variables declaration//GEN-END:variables
}
